services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=off
    volumes:
      - ./vpn-config:/data/vpn
    restart: unless-stopped
    networks:
      - outside
      - isolated

  primary-algorithm:
    build: ./primary-algorithm/
    networks:
      - isolated

  seondary-algorithm:
      build: ./secondary-algorithm/
      networks:
        - isolated

networks:
  outside:
  isolated: