services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=on
      - SUBNETS=172.16.238.0/24,172.18.238.0/24,172.17.0.1
    volumes:
      - ./vpn-config/:/data/vpn/
    restart: unless-stopped
    networks:
      - outside
      - isolated

  primary-algorithm:
    volumes:
      - ./primary-algorithm:/app
    build: ./algorithm-base
    networks:
      - isolated
    command: bash -c "pip install -r requirements.txt && python primary.py"

  secondary-algorithm:
    volumes:
      - ./secondary-algorithm:/app
    build: ./algorithm-base
    networks:
      - isolated
    command: bash -c "pip install -r requirements.txt && python secondary.py"

networks:
  outside:
    ipam:
      config:
        - subnet: "172.18.238.0/24"
  isolated:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
