services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - KILL_SWITCH=off
      - SUBNETS=192.168.0.0/24
    volumes:
      - ./vpn-config/:/data/vpn/
    restart: unless-stopped
    networks:
      - outside
      - isolated

  primary-algorithm:
    volumes:
      - ./primary-algorithm:/app
    build: ./algorithm-base
    networks:
      - isolated
    command: bash -c "pip install -r requirements.txt && python primary.py"

  secondary-algorithm:
    volumes:
      - ./secondary-algorithm:/app
    build: ./algorithm-base
    networks:
      - isolated
    command: bash -c "pip install -r requirements.txt && python secondary.py"

networks:
  outside:

  isolated:

